### ISSUE TITLE
E-Auto: Verbrauch und Stromkosten pro Kilometer

### ISSUE THREAD

**Issue by ledermann** [solectrus/solectrus#3517]
Wer ein E-Auto hat, möchte wissen, wie viel Strom für einen gefahrenen Kilometer verbraucht wird, welche Kosten dafür entstehen und wie sich das im Laufe der Zeit verändert. 

Das E-Auto selbst zeigt den Verbrauch üblicherweise an, aber der Wert ist oft ungenau (enthält z.B. keine Ladeverluste) und wird auch nicht historisch gespeichert.

## Benötigte Informationen

Um dies berechnen zu können, werden folgende Informationen benötigt:

- Gefahrene **Kilometer** (aus der API des E-Autos)
- Geladene **Energie** für das E-Auto (in kWh). Aus der eigenen Wallbox oder extern geladen (z.B. an Ladesäulen)
- Entstandene **Kosten** der Energie (in EUR). Bei der eigenen Wallbox über den Power-Splitter berechnet, bei externen Ladevorgängen manuell einzugeben.

## Ausgabe

Bei der Wahl eines Betrachtungszeitraums (Tag, Woche, Monat, Jahr, Gesamt) soll SOLECTRUS die folgenden Werte berechnen und anzeigen:

- Fahrleistung (in km)
- Verbrauch (in kWh pro 100km oder Wh/km)
- Kosten (in EUR pro km und EUR gesamt)

## TODO

- [ ] Zusätzlicher Sensor für die Fahrleistung (km) des E-Autos
- [ ] Eingabemöglichkeit für externe Ladevorgänge: Datum, Energie in kWh, Kosten in EUR, Ort
- [ ] Eingabemöglichkeit für Ladevorgänge über die Wallbox, die nicht zu berücksichtigen sind, weil die Wallbox z.B. von Gästen benutzt wurde: Datum, Energie in kWh, Notiz 
- [ ] Darstellung der Fahrleistung in km für den gewählten Zeitraum
- [ ] Darstellung des Verbrauchs in kWh pro 100km für den gewählten Zeitraum
- [ ] Darstellung der Kosten in EUR (pro km und gesamt) für den gewählten Zeitraum
- [ ] Darstellung des Verbrauchs als Diagramm (Säulen mit kWh pro 100km)
- [ ] Darstellung der Kosten als Diagramm (Säulen mit EUR pro km bzw. EUR gesamt)

## Ausbaustufen

Wer die Fahrleistung nicht automatisiert abrufen kann, sollte die Möglichkeit einer manuellen Erfassung haben. Hier dürfte es genügen, einmal im Monat den Kilometerstand abzulesen und einzugeben.

**Comment by megaholti** [comment]
netter Aspekt, wichtig wäre aber auch die Kosten, oder vielmehr die Ersparnis durch das E-fahrzeug in die Amositationsberechnung mit aufzunehmen, bzw. einzurechnen. Das geht da aktuell komplett unter

**Comment by ledermann** [comment]
@megaholti In der [Amortisationsberechnung](https://github.com/solectrus/solectrus/issues/2416) geht es darum, wann sich die PV-Anlage gerechnet haben wird (also PV-Module, Wechselrichter, Akkus). Ob und wie einzelne Verbraucher (wie ein E-Auto) sich auswirken, ist dafür unerheblich.

Die Ersparnis eines E-Autos (verglichen mit einem Verbrenner) ist ein anderes Thema, das ich aber auch angehen möchte, siehe solectrus/solectrus#2407.

**Comment by megaholti** [comment]
Sicher, das ist nett, allerdings finde ich noch immer dass zu einer Amotisationsberechnung die Ersparnis durch eventuell vorhandene Elektrofahrzeuge gehört, da die Berechnung sich schlagartig um mehrere Monate oder Jahre zum Gusten des Anlagenbetreibers verändert.

**Comment by ledermann** [comment]
@megaholti Ich diskutiere da gerne drüber. Damit wir die Themen nicht vermischen (was mir die Implementierung von Issues sehr erschwert), habe ich ein separates Thema angelegt: https://github.com/orgs/solectrus/discussions/5796
